FROM node:16.13.2-alpine

# カレントワーキングディレクトリとして 'app' フォルダを指定する
WORKDIR /app/

# `package.json` と `package-lock.json` （あれば）を両方コピーする
COPY package*.json ./

# プロジェクトの依存ライブラリをインストールする
RUN npm install

# カレントワーキングディレクトリ(つまり 'app' フォルダ)にプロジェクトのファイルやフォルダをコピーする
COPY . .



