FROM python:3.10-alpine

ENV APP_HOME=/home/app/web
RUN mkdir -p ${APP_HOME}
WORKDIR ${APP_HOME}

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apk add --no-cache gcc g++ musl-dev openblas-dev

RUN pip install --upgrade pip
COPY ./requirements.dev.txt .
RUN pip install -r requirements.dev.txt

COPY . . 